FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY mvnw .
RUN ./mvnw clean package -DskipTests

EXPOSE 4000

CMD ["java", "-jar", "target/backend-java-0.0.1-SNAPSHOT.jar", "--server.port=4000"]