FROM eclipse-temurin:21-jdk-alpine

# Install Maven
RUN apk add --no-cache maven bash

WORKDIR /app

# Copy project files
COPY pom.xml .
COPY src ./src

# Build the project
RUN mvn clean package -DskipTests

# Expose port
EXPOSE 4000

# Run Spring Boot
CMD ["java", "-jar", "target/backend-java-0.0.1-SNAPSHOT.jar", "--server.port=4000"]