# Use official Java 21 runtime
FROM eclipse-temurin:21-jdk-alpine

# Set working directory
WORKDIR /app

# Copy pom.xml and src folder from current folder
COPY pom.xml .
COPY src ./src

# Build the project using Maven wrapper
RUN ./mvnw clean package -DskipTests

# Expose port 4000
EXPOSE 4000

# Run the Spring Boot application
CMD ["java", "-jar", "target/backend-java-0.0.1-SNAPSHOT.jar", "--server.port=4000"]